package ejemplobd_jdbc;

import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class ContactoDialogo extends javax.swing.JDialog {

    private Contacto contacto;
    private boolean aceptado = false;
    private boolean hayCambios = false;

    /**
     * Obtiene los datos del contacto con las modificaciones que haya realizado
     * el usuario en esta ventana
     * 
     * @return Objeto Contacto con los datos que se hayan actualizado en la ventana
     */
    public Contacto getContacto() {
        return contacto;
    }

    /**
     * Permite asignar los datos de un contacto a esta ventana de diálogo, de
     * manera que las modificaciones que realice el usuario se reflejarán
     * en el objeto pasado por parámetro
     * 
     * @param contacto Objeto Contacto que contiene los datos que se mostrarán
     * en la ventana.
     */
    public void setContacto(Contacto contacto) {
        this.contacto = contacto;
        if(contacto.getIdContacto()!=0) {
            jLabelIdentificador.setText(String.valueOf(contacto.getIdContacto()));
        } else {
            jLabelIdentificador.setText("Nuevo");
        }        
        jTextFieldNombre.setText(contacto.getNombre());
        jTextFieldApellidos.setText(contacto.getApellidos());
        jTextFieldTelefono.setText(contacto.getTelefono());
        jTextFieldCorreo.setText(contacto.getCorreo());
    }

    /**
     * Permite conocer si el usuario ha pulsado el botón Aceptar al salir de 
     * esta ventana
     * 
     * @return true si el usuario ha pulsado Aceptar y false si ha pulsado Cancelar
     */
    public boolean isAceptado() {
        return aceptado;
    }
    
    /**
     * Creates new form ContactoDialogo
     */
    public ContactoDialogo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Impedir el cierre de la ventana pulsando la X para obligar a Aceptar o Cancelar
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        //Centrar la ventana en función de la ventana padre
        this.setLocationRelativeTo(parent);
        //Cambiar el título de la ventana
        this.setTitle("Datos del contacto");
    }
    
    public void activarCampos(boolean activar) {
        jTextFieldNombre.setEnabled(activar);
        jTextFieldApellidos.setEnabled(activar);
        jTextFieldTelefono.setEnabled(activar);
        jTextFieldCorreo.setEnabled(activar);
        if(activar) hayCambios=true;
    }
    
    private void aceptar() {
        aceptado = true;
        //Si todos los datos que ha introducido el usuario cumplen con
        //  los tamaños establecidos, se cierra la ventana. En caso contrario,
        //  se avisa al usuario del problema y se mantiene en la ventana
        if(comprobarCampoTexto(jTextFieldNombre, Contacto.TAM_NOMBRE) &&
                comprobarCampoTexto(jTextFieldApellidos, Contacto.TAM_APELLIDOS) &&
                comprobarCampoTexto(jTextFieldTelefono, Contacto.TAM_TELEFONO) &&
                comprobarCampoTexto(jTextFieldCorreo, Contacto.TAM_CORREO)) {
            contacto.setNombre(jTextFieldNombre.getText());
            contacto.setApellidos(jTextFieldApellidos.getText());
            contacto.setTelefono(jTextFieldTelefono.getText());
            contacto.setCorreo(jTextFieldCorreo.getText());
            this.setVisible(false);
        }
    }

    private void cancelar() {
        aceptado = false;
        this.setVisible(false);        
    }
    
    private boolean comprobarCampoTexto(JTextField jTextField, int tamañoMax) {
        //Comprobar si el tamaño del texto excede el tamaño permitido
        if(jTextField.getText().length() > tamañoMax) {
            JOptionPane.showMessageDialog(this, 
                    "El tamaño del dato excede el tamaño máximo permitido", 
                    "Atención", JOptionPane.WARNING_MESSAGE); 
            //Dejar seleccionado el trozo de texto que sobra
            jTextField.setSelectionStart(tamañoMax);
            jTextField.setSelectionEnd(jTextField.getText().length());
            jTextField.requestFocus();
            return false;
        } else {
            return true;
        }
            
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelIdentificador = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTextFieldNombre.setColumns(15);
        jTextFieldNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNombreMouseClicked(evt);
            }
        });

        jLabel1.setText("Identificador:");

        jLabel6.setText("Correo:");

        jLabel3.setText("Nombre:");

        jTextFieldCorreo.setColumns(15);
        jTextFieldCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCorreoMouseClicked(evt);
            }
        });

        jLabelIdentificador.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabelIdentificador.setText(" ");

        jLabel5.setText("Teléfono:");

        jTextFieldTelefono.setColumns(10);
        jTextFieldTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldTelefonoMouseClicked(evt);
            }
        });

        jLabel4.setText("Apellidos:");

        jTextFieldApellidos.setColumns(20);
        jTextFieldApellidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldApellidosMouseClicked(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 231, Short.MAX_VALUE)
                        .addComponent(jButtonGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNombre)
                                    .addComponent(jLabelIdentificador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jTextFieldApellidos)
                            .addComponent(jTextFieldTelefono)
                            .addComponent(jTextFieldCorreo))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabelIdentificador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        aceptar();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(hayCambios) {
            int respuesta = JOptionPane.showConfirmDialog(this, 
                    "¿Desea guardar los cambios?", 
                    "Atención", JOptionPane.YES_NO_CANCEL_OPTION, 
                    JOptionPane.INFORMATION_MESSAGE);
            switch(respuesta) {
                case JOptionPane.YES_OPTION:
                    aceptar();
                    break;
                case JOptionPane.NO_OPTION:
                    cancelar();
                    break;
                case JOptionPane.CANCEL_OPTION:
                    break;
            }
        } else {
            cancelar();
        }
    }//GEN-LAST:event_formWindowClosing

    private void jTextFieldNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNombreMouseClicked
        jTextFieldNombre.setEnabled(true);
        jTextFieldNombre.requestFocus();
        hayCambios = true;
    }//GEN-LAST:event_jTextFieldNombreMouseClicked

    private void jTextFieldApellidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldApellidosMouseClicked
        jTextFieldApellidos.setEnabled(true);
        jTextFieldApellidos.requestFocus();
        hayCambios = true;
    }//GEN-LAST:event_jTextFieldApellidosMouseClicked

    private void jTextFieldTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoMouseClicked
        jTextFieldTelefono.setEnabled(true);
        jTextFieldTelefono.requestFocus();
        hayCambios = true;
    }//GEN-LAST:event_jTextFieldTelefonoMouseClicked

    private void jTextFieldCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCorreoMouseClicked
        jTextFieldCorreo.setEnabled(true);
        jTextFieldCorreo.requestFocus();
        hayCambios = true;
    }//GEN-LAST:event_jTextFieldCorreoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactoDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactoDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactoDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactoDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ContactoDialogo dialog = new ContactoDialogo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelIdentificador;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
