/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplobd_jdbc;

import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JOptionPane;

class DialogoConfiguracion extends javax.swing.JDialog {

    Properties propiedades = new Properties();    

    /**
     * Creates new form DialogoConfiguracion
     */
    public DialogoConfiguracion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);        
        initComponents();
        jTextFieldServidor.setEnabled(false);
        jTextFieldBD.setEnabled(false);
        jTextFieldUsuario.setEnabled(false);
        jTextFieldPassword.setEnabled(false);        
        this.setLocationRelativeTo(parent);        
        try {
            FileReader fichProp = new FileReader("agenda.cfg");
            propiedades.load(fichProp);  
            if(propiedades.getProperty("protocolo")!=null &&
                    propiedades.getProperty("protocolo").equals("jdbc:mysql://")) {
                jRadioButtonMySQL.setSelected(true);
                
                jTextFieldServidor.setEnabled(true);
                jTextFieldBD.setEnabled(true);
                jTextFieldUsuario.setEnabled(true);
                jTextFieldPassword.setEnabled(true);   
                
                jTextFieldServidor.setText(propiedades.getProperty("servidor"));
                jTextFieldBD.setText(propiedades.getProperty("BD"));
                jTextFieldUsuario.setText(propiedades.getProperty("usuario"));
                jTextFieldPassword.setText(propiedades.getProperty("password"));
            } else {
                jRadioButtonDerby.setSelected(false);
                
                jTextFieldServidor.setEnabled(false);
                jTextFieldBD.setEnabled(false);
                jTextFieldUsuario.setEnabled(false);
                jTextFieldPassword.setEnabled(false);   
                
                jTextFieldServidor.setText("");
                jTextFieldBD.setText("");
                jTextFieldUsuario.setText("");
                jTextFieldPassword.setText("");
            }
        } catch(IOException e) {
            jTextFieldServidor.setText("");
            jTextFieldBD.setText("");
            jTextFieldUsuario.setText("");
            jTextFieldPassword.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldServidor = new javax.swing.JTextField();
        jTextFieldBD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPassword = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();
        jRadioButtonDerby = new javax.swing.JRadioButton();
        jRadioButtonMySQL = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuración");
        setResizable(false);

        jLabel1.setText("Servidor MySQL:");

        jTextFieldServidor.setText("jTextFieldServidor");

        jTextFieldBD.setText("jTextFieldBD");

        jLabel2.setText("Base de datos:");

        jLabel3.setText("Usuario:");

        jTextFieldUsuario.setText("jTextFieldUsuario");

        jLabel4.setText("Contraseña:");

        jTextFieldPassword.setText("jTextFieldPassword");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonDerby);
        jRadioButtonDerby.setSelected(true);
        jRadioButtonDerby.setText("Base de datos interna");
        jRadioButtonDerby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDerbyActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonMySQL);
        jRadioButtonMySQL.setText("Base de datos de servidor MySQL");
        jRadioButtonMySQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMySQLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldServidor)
                            .addComponent(jTextFieldBD)
                            .addComponent(jTextFieldUsuario)
                            .addComponent(jTextFieldPassword)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonMySQL)
                            .addComponent(jRadioButtonDerby))
                        .addGap(0, 85, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButtonDerby)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonMySQL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        try {
            Properties propiedades = new Properties();
            FileWriter fichProp = new FileWriter("agenda.cfg");
            if(jRadioButtonDerby.isSelected()) {
                propiedades.setProperty("protocolo", "jdbc:derby://");   
                propiedades.store(fichProp, null);
                this.setVisible(false);
            } else {
                propiedades.setProperty("protocolo", "jdbc:mysql://");
                propiedades.setProperty("servidor", jTextFieldServidor.getText());
                propiedades.setProperty("BD", jTextFieldBD.getText());
                propiedades.setProperty("usuario", jTextFieldUsuario.getText());
                propiedades.setProperty("password", jTextFieldPassword.getText());
                propiedades.store(fichProp, null);
                this.setVisible(false);
            }
/*            JOptionPane.showMessageDialog(this, 
                    "Debe iniciar de nuevo la aplicación\n"
                    + "para que la nueva configuración tenga efecto", 
                    "Reiniciar", JOptionPane.INFORMATION_MESSAGE);
            System.exit(0);*/
        } catch(IOException e) {
            JOptionPane.showMessageDialog(this, 
                    "No se ha podido guardar la configuración,\n"
                    + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jRadioButtonMySQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMySQLActionPerformed
        jTextFieldServidor.setEnabled(true);
        jTextFieldBD.setEnabled(true);
        jTextFieldUsuario.setEnabled(true);
        jTextFieldPassword.setEnabled(true);    
        
        jTextFieldServidor.setText(propiedades.getProperty("servidor"));
        jTextFieldBD.setText(propiedades.getProperty("BD"));
        jTextFieldUsuario.setText(propiedades.getProperty("usuario"));
        jTextFieldPassword.setText(propiedades.getProperty("password"));        
    }//GEN-LAST:event_jRadioButtonMySQLActionPerformed

    private void jRadioButtonDerbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDerbyActionPerformed
        jTextFieldServidor.setEnabled(false);
        jTextFieldBD.setEnabled(false);
        jTextFieldUsuario.setEnabled(false);
        jTextFieldPassword.setEnabled(false);
        
        jTextFieldServidor.setText("");
        jTextFieldBD.setText("");
        jTextFieldUsuario.setText("");
        jTextFieldPassword.setText("");        
    }//GEN-LAST:event_jRadioButtonDerbyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                DialogoConfiguracion dialog = new DialogoConfiguracion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButtonDerby;
    private javax.swing.JRadioButton jRadioButtonMySQL;
    private javax.swing.JTextField jTextFieldBD;
    private javax.swing.JTextField jTextFieldPassword;
    private javax.swing.JTextField jTextFieldServidor;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
