/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplobd_jdbc;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.*;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.swing.JRViewer;

public class Inicio extends javax.swing.JFrame {

    private String VERSION = "1.1";
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        try {
            //Cambiar el icono de la aplicación
            InputStream imgStream = this.getClass().getResourceAsStream("/icons/logo.png"); 
            BufferedImage bi = ImageIO.read(imgStream); 
            ImageIcon myImg = new ImageIcon(bi); 
            this.setIconImage(myImg.getImage()); 
            //Establecer el aspecto de ventanas del sistema operativo actual
            JFrame.setDefaultLookAndFeelDecorated(true);
            JDialog.setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(IOException e) {
            //No se ha podido cargar el icono de la aplicación
            e.printStackTrace();
        } catch(Exception e) {
            //No se ha podido cargar el aspecto del sistema operactivo
            e.printStackTrace();
        }
        
        initComponents();
        
        //Centrar la ventana en la pantalla
        this.setLocationRelativeTo(null);
        //Cambiar el título de la ventana
        this.setTitle("Agenda de contactos v"+VERSION);
        //Si no estamos en el diseño de NetBeans se cargan los datos
        //Esto evita problemas cuando se arrastra el panel a la ventana durante el diseño
        //  ya que durante el diseño no debe conectarse con la BD ni obtener datos
        if(!java.beans.Beans.isDesignTime()) {
            //Conectar con la base de datos
            BDAgenda.conectarBDAgenda();
            //Rellenar lista de contactos        
            panelListaContactos1.CargarDatosJTable();   
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelListaContactos1 = new ejemplobd_jdbc.ContactoListaPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemConfiguración = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemNuevoContacto = new javax.swing.JMenuItem();
        jMenuItemEditarContacto = new javax.swing.JMenuItem();
        jMenuItemSuprimirContacto = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItemApellidos = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemNombre = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemRecientes = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemAntiguos = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemListadoApellidos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemCopia = new javax.swing.JMenuItem();
        jMenuItemRestaurar = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemContactos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ejemplo de aplicación de gestión de Bases de Datos");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Desarrollada para el Ciclo Formativo de");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Desarrollo de Aplicaciones Web");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logo.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("I.E.S. Ntra. Sra. de los Remedios (Ubrique)");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.blue);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Agenda de Contactos");

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Javier García Escobedo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inicio", jPanel1);
        jTabbedPane1.addTab("Contactos", panelListaContactos1);

        jMenu1.setMnemonic('A');
        jMenu1.setText("Agenda");
        jMenu1.setToolTipText("");

        jMenuItemConfiguración.setMnemonic('C');
        jMenuItemConfiguración.setText("Configuración...");
        jMenuItemConfiguración.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConfiguraciónActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemConfiguración);

        jMenuItemSalir.setMnemonic('S');
        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('C');
        jMenu2.setText("Contactos");

        jMenuItemNuevoContacto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_INSERT, 0));
        jMenuItemNuevoContacto.setMnemonic('N');
        jMenuItemNuevoContacto.setText("Nuevo...");
        jMenuItemNuevoContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoContactoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemNuevoContacto);

        jMenuItemEditarContacto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemEditarContacto.setMnemonic('E');
        jMenuItemEditarContacto.setText("Editar...");
        jMenuItemEditarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarContactoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemEditarContacto);

        jMenuItemSuprimirContacto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        jMenuItemSuprimirContacto.setMnemonic('S');
        jMenuItemSuprimirContacto.setText("Suprimir...");
        jMenuItemSuprimirContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSuprimirContactoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemSuprimirContacto);
        jMenu2.add(jSeparator5);

        jMenu3.setMnemonic('O');
        jMenu3.setText("Orden");

        buttonGroup1.add(jRadioButtonMenuItemApellidos);
        jRadioButtonMenuItemApellidos.setMnemonic('A');
        jRadioButtonMenuItemApellidos.setSelected(true);
        jRadioButtonMenuItemApellidos.setText("Apellidos");
        jRadioButtonMenuItemApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemApellidosActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItemApellidos);

        buttonGroup1.add(jRadioButtonMenuItemNombre);
        jRadioButtonMenuItemNombre.setMnemonic('N');
        jRadioButtonMenuItemNombre.setText("Nombre");
        jRadioButtonMenuItemNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemNombreActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItemNombre);

        buttonGroup1.add(jRadioButtonMenuItemRecientes);
        jRadioButtonMenuItemRecientes.setMnemonic('R');
        jRadioButtonMenuItemRecientes.setText("Recientes");
        jRadioButtonMenuItemRecientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemRecientesActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItemRecientes);

        buttonGroup1.add(jRadioButtonMenuItemAntiguos);
        jRadioButtonMenuItemAntiguos.setMnemonic('A');
        jRadioButtonMenuItemAntiguos.setText("Antigüos");
        jRadioButtonMenuItemAntiguos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemAntiguosActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItemAntiguos);

        jMenu2.add(jMenu3);

        jMenuBar1.add(jMenu2);

        jMenu4.setMnemonic('I');
        jMenu4.setText("Informes");

        jMenuItemListadoApellidos.setMnemonic('L');
        jMenuItemListadoApellidos.setText("Listado de contactos por apellidos");
        jMenuItemListadoApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListadoApellidosActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemListadoApellidos);

        jMenuBar1.add(jMenu4);

        jMenu5.setMnemonic('H');
        jMenu5.setText("Herramientas");

        jMenuItemCopia.setMnemonic('C');
        jMenuItemCopia.setText("Copia de seguridad...");
        jMenuItemCopia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCopiaActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemCopia);

        jMenuItemRestaurar.setMnemonic('R');
        jMenuItemRestaurar.setText("Restaurar copia...");
        jMenuItemRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRestaurarActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemRestaurar);

        jMenuBar1.add(jMenu5);

        jMenu6.setMnemonic('V');
        jMenu6.setText("Ventana");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setMnemonic('I');
        jMenuItem1.setText("Inicio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuItemContactos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemContactos.setMnemonic('C');
        jMenuItemContactos.setText("Contactos");
        jMenuItemContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContactosActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemContactos);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemConfiguraciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfiguraciónActionPerformed
        DialogoConfiguracion dialogConfig = new DialogoConfiguracion(this, true);
        dialogConfig.setVisible(true);
        dialogConfig.dispose();
        BDAgenda.conectarBDAgenda();
        panelListaContactos1.CargarDatosJTable();
    }//GEN-LAST:event_jMenuItemConfiguraciónActionPerformed

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        //Cerrar la ventana
        this.dispose();
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemNuevoContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoContactoActionPerformed
        panelListaContactos1.nuevo();
        //Mostrar el panel de la lista de contactos
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jMenuItemNuevoContactoActionPerformed

    private void jMenuItemEditarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarContactoActionPerformed
        panelListaContactos1.editar();
        //Mostrar el panel de la lista de contactos
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jMenuItemEditarContactoActionPerformed

    private void jMenuItemSuprimirContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSuprimirContactoActionPerformed
        panelListaContactos1.suprimir();
        //Mostrar el panel de la lista de contactos
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jMenuItemSuprimirContactoActionPerformed

    private void jRadioButtonMenuItemApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemApellidosActionPerformed
        panelListaContactos1.setOrdenContactos(BDAgenda.ORDEN_APELLIDOS);
        panelListaContactos1.CargarDatosJTable();
        //Mostrar el panel de la lista de contactos
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jRadioButtonMenuItemApellidosActionPerformed

    private void jRadioButtonMenuItemNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemNombreActionPerformed
        panelListaContactos1.setOrdenContactos(BDAgenda.ORDEN_NOMBRE);
        panelListaContactos1.CargarDatosJTable();
        //Mostrar el panel de la lista de contactos
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jRadioButtonMenuItemNombreActionPerformed

    private void jRadioButtonMenuItemRecientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemRecientesActionPerformed
        panelListaContactos1.setOrdenContactos(BDAgenda.ORDEN_RECIENTES);
        panelListaContactos1.CargarDatosJTable();
        //Mostrar el panel de la lista de contactos
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jRadioButtonMenuItemRecientesActionPerformed

    private void jRadioButtonMenuItemAntiguosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemAntiguosActionPerformed
        panelListaContactos1.setOrdenContactos(BDAgenda.ORDEN_ANTIGUOS);
        panelListaContactos1.CargarDatosJTable();
        //Mostrar el panel de la lista de contactos
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jRadioButtonMenuItemAntiguosActionPerformed

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
        //Mostrar el panel de la lista de contactos
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jMenuItemListadoApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListadoApellidosActionPerformed
        try
        {
            InputStream in = getClass().getClassLoader().getResourceAsStream("informes/ListadoContactos.jasper");
            JasperReport report = (JasperReport) JRLoader.loadObject(in);

            //Rellenar el informe con datos
            Connection conexion = BDAgenda.conexion;
            Map parametros = new HashMap();
            //Si hiciera falta indicar parámetros:
            //  parámetros.put("nombreParametro", valor);
            JasperPrint reportRelleno = JasperFillManager.fillReport(report, parametros, conexion);

            //Mostrar el informe
            JDialog viewer = new JDialog(this, "Vista previa del documento", true);
            viewer.setSize(800,600);
            viewer.setLocationRelativeTo(null);
            JRViewer jrv = new JRViewer(reportRelleno);
            viewer.getContentPane().add(jrv);
            viewer.setVisible(true);
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.toString());
            e.printStackTrace();
        }

            
    }//GEN-LAST:event_jMenuItemListadoApellidosActionPerformed

    private void jMenuItemCopiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCopiaActionPerformed
        JFileChooser jfc = new JFileChooser();
        int respuesta = jfc.showSaveDialog(this);
        if(respuesta == JFileChooser.APPROVE_OPTION) {
            if(jfc.getSelectedFile().exists()) {
                int respuesta2 = JOptionPane.showConfirmDialog(this, 
                        "El fichero seleccionado ya existe.\n"
                        + "¿Desea eliminar su contenido?", 
                        "Atención", JOptionPane.YES_NO_OPTION, 
                        JOptionPane.WARNING_MESSAGE);
                if(respuesta2 == JOptionPane.NO_OPTION)
                    return;
            }
            BDAgenda.copiaSeguridad(jfc.getSelectedFile());
        }
    }//GEN-LAST:event_jMenuItemCopiaActionPerformed

    private void jMenuItemRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRestaurarActionPerformed
        int respuesta1 = JOptionPane.showConfirmDialog(this, 
                "Esta operación eliminará el contenido actual\n"
                + "¿Desea continuar?", "Atención", JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE);
        if(respuesta1 == JOptionPane.YES_OPTION) {
            JFileChooser jfc = new JFileChooser();
            int respuesta = jfc.showOpenDialog(this);
            if(respuesta == JFileChooser.APPROVE_OPTION) {
                BDAgenda.borrarBaseDatos();
                BDAgenda.restaurarCopia(jfc.getSelectedFile());
                //Rellenar lista de contactos en pantalla
                panelListaContactos1.CargarDatosJTable();   
            }
        }
    }//GEN-LAST:event_jMenuItemRestaurarActionPerformed

    private void jMenuItemContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContactosActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jMenuItemContactosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemConfiguración;
    private javax.swing.JMenuItem jMenuItemContactos;
    private javax.swing.JMenuItem jMenuItemCopia;
    private javax.swing.JMenuItem jMenuItemEditarContacto;
    private javax.swing.JMenuItem jMenuItemListadoApellidos;
    private javax.swing.JMenuItem jMenuItemNuevoContacto;
    private javax.swing.JMenuItem jMenuItemRestaurar;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenuItem jMenuItemSuprimirContacto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemAntiguos;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemApellidos;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemNombre;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemRecientes;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private ejemplobd_jdbc.ContactoListaPanel panelListaContactos1;
    // End of variables declaration//GEN-END:variables
}
